# This file contains the build settings for your Netlify site.
# It ensures that Netlify uses the correct command to build your Next.js site
# and knows where to find the output files.

# This file contains the build settings for your Netlify site.
# It ensures that Netlify uses the correct command to build your Next.js site
# and knows where to find the output files.

[build]
  # The command to build your site
  command = "npm run build"

  # The directory where the built site is located
  publish = "out"

  # The base directory where the site's code is located
  base = "web-audit-mvp"

# Required for Next.js API routes to work on Netlify
[[redirects]]
  from = "/api/audit"
  to = "/.netlify/functions/audit"
  status = 200
  force = false

# Handle client-side routing - let Next.js handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
