# This file contains the build settings for your Netlify site.
# It ensures that Netlify uses the correct command to build your Next.js site
# and knows where to find the output files.

# This file contains the build settings for your Netlify site.
# It ensures that Netlify uses the correct command to build your Next.js site
# and knows where to find the output files.

[build]
  command = "npm run build"
  publish = ".next"
  base = "web-audit-mvp"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functions_src = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
